import Head from "next/head";
import { Yoyogi } from "../components/components";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Yoyogi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Yoyogi />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
